spring.application.name=nexus-eureka-server
server.port=${SERVER_PORT:8761}

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.enabled=true
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
eureka.server.default-open-for-traffic-count=0

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=Nexus Eureka Server
info.app.description=Registro y descubrimiento de Hotel Nexus
